db: biu
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 19961225
logging:
  path: ./logs
  level:
    com.abc.dao: debug
